export const productList =[
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Nissan Altima',
        carSubtitle: 'Midsize Sedan, Reliable',
        price: 20000,
        mileage: '24,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Nissan',
        model: 'Altima',
        year: 2019,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Audi A4',
        carSubtitle: 'Luxury Sedan, Premium Features',
        price: 35000,
        mileage: '15,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '3.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Audi',
        model: 'A4',
        year: 2022,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Hyundai Tucson',
        carSubtitle: 'Compact SUV, Spacious Interior',
        price: 22000,
        mileage: '22,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '2.4 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'SUV',
        brand: 'Hyundai',
        model: 'Tucson',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Mercedes-Benz C-Class',
        carSubtitle: 'Luxury Sedan, Elegance and Style',
        price: 40000,
        mileage: '12,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2022,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ford F-250',
        carSubtitle: 'Heavy-Duty Pickup Truck',
        price: 42000,
        mileage: '38,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '6.2 L',
        engineType: 'Diesel',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Ford',
        model: 'F-250',
        year: 2020,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Chevrolet Cruze',
        carSubtitle: 'Compact Car, Affordable and Efficient',
        price: 17000,
        mileage: '26,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '1.4 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Compact',
        brand: 'Chevrolet',
        model: 'Cruze',
        year: 2019,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ram 1500',
        carSubtitle: 'Full-Size Pickup Truck, Tough and Rugged',
        price: 32000,
        mileage: '30,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '5.7 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Ram',
        model: '1500',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Lexus ES',
        carSubtitle: 'Luxury Sedan, Premium Comfort',
        price: 38000,
        mileage: '14,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '3.5 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Lexus',
        model: 'ES',
        year: 2022,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Harley-Davidson Sportster',
        carSubtitle: 'Cruiser Motorcycle, Classic Style',
        price: 15000,
        mileage: '8,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '1.2 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Harley-Davidson',
        model: 'Sportster',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Toyota Corolla',
        carSubtitle: 'Compact Car, Reliable and Fuel-Efficient',
        price: 19000,
        mileage: '20,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '1.8 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Compact',
        brand: 'Toyota',
        model: 'Corolla',
        year: 2020,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Chevrolet Silverado',
        carSubtitle: 'Full-Size Pickup Truck, Powerful',
        price: 38000,
        mileage: '30,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '5.3 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Chevrolet',
        model: 'Silverado',
        year: 2021,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Yamaha YZF-R6',
        carSubtitle: 'Sport Motorcycle, High Performance',
        price: 11000,
        mileage: '6,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '0.6 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Yamaha',
        model: 'YZF-R6',
        year: 2020,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Honda Accord',
        carSubtitle: 'Midsize Sedan, Comfort and Style',
        price: 22000,
        mileage: '18,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Honda',
        model: 'Accord',
        year: 2021,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ducati Monster',
        carSubtitle: 'Naked Bike, Aggressive Design',
        price: 14000,
        mileage: '7,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '0.8 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Ducati',
        model: 'Monster',
        year: 2022,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Subaru Outback',
        carSubtitle: 'Crossover SUV, All-Wheel Drive',
        price: 28000,
        mileage: '16,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '2.4 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Crossover SUV',
        brand: 'Subaru',
        model: 'Outback',
        year: 2020,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Kawasaki Ninja',
        carSubtitle: 'Sport Motorcycle, Race-Ready',
        price: 12000,
        mileage: '5,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '0.6 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Kawasaki',
        model: 'Ninja',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Volvo XC90',
        carSubtitle: 'Luxury SUV, Scandinavian Elegance',
        price: 36000,
        mileage: '22,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'SUV',
        brand: 'Volvo',
        model: 'XC90',
        year: 2022,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'BMW S1000RR',
        carSubtitle: 'Superbike, Precision Engineering',
        price: 18000,
        mileage: '4,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '1.0 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'BMW',
        model: 'S1000RR',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Chevrolet Malibu',
        carSubtitle: 'Midsize Sedan, Stylish and Comfortable',
        price: 23000,
        mileage: '26,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Chevrolet',
        model: 'Malibu',
        year: 2020,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Dodge Ram 2500',
        carSubtitle: 'Heavy-Duty Pickup Truck, Rugged Performance',
        price: 42000,
        mileage: '30,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '6.4 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Dodge',
        model: 'Ram 2500',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Hyundai Sonata',
        carSubtitle: 'Midsize Sedan, Affordable Luxury',
        price: 21000,
        mileage: '22,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Hyundai',
        model: 'Sonata',
        year: 2021,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ford Ranger',
        carSubtitle: 'Midsize Pickup Truck, Versatile',
        price: 32000,
        mileage: '25,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '2.3 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Ford',
        model: 'Ranger',
        year: 2022,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Mercedes-Benz E-Class',
        carSubtitle: 'Luxury Sedan, Elegant Design',
        price: 38000,
        mileage: '18,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Mercedes-Benz',
        model: 'E-Class',
        year: 2022,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Chevrolet Colorado',
        carSubtitle: 'Midsize Pickup Truck, Reliable Workhorse',
        price: 29000,
        mileage: '27,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '3.6 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Chevrolet',
        model: 'Colorado',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Toyota RAV4',
        carSubtitle: 'Compact SUV, Adventure-Ready',
        price: 26000,
        mileage: '23,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '2.5 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'SUV',
        brand: 'Toyota',
        model: 'RAV4',
        year: 2020,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ram 3500',
        carSubtitle: 'Heavy-Duty Pickup Truck, Towing Power',
        price: 45000,
        mileage: '35,000 km',
        location: 'Malmö, Sverige',
        engineVolume: '6.7 L',
        engineType: 'Diesel',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Ram',
        model: '3500',
        year: 2020,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Nissan Rogue',
        carSubtitle: 'Compact SUV, Spacious and Comfortable',
        price: 23000,
        mileage: '21,000 km',
        location: 'Gothenburg, Sverige',
        engineVolume: '2.0 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'SUV',
        brand: 'Nissan',
        model: 'Rogue',
        year: 2021,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'GMC Sierra',
        carSubtitle: 'Full-Size Pickup Truck, Refined Interior',
        price: 39000,
        mileage: '28,000 km',
        location: 'Stockholm, Sverige',
        engineVolume: '6.2 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'GMC',
        model: 'Sierra',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Speedboat X1',
        carSubtitle: 'Sport Boat, High Speed',
        price: 30000,
        mileage: '50 hours',
        location: 'Miami, FL',
        engineVolume: '250 HP',
        engineType: 'Gasoline',
        brand: 'Speedboat',
        model: 'X1',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Luxury Yacht 720',
        carSubtitle: 'Yacht, Elegance and Comfort',
        price: 150000,
        mileage: '100 hours',
        location: 'Los Angeles, CA',
        engineVolume: '600 HP',
        engineType: 'Diesel',
        brand: 'Luxury Yacht',
        model: '720',
        year: 2021,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Jet Ski Pro 300',
        carSubtitle: 'Personal Watercraft, Thrilling Ride',
        price: 8000,
        mileage: '20 hours',
        location: 'New York, NY',
        engineVolume: '100 HP',
        engineType: 'Gasoline',
        brand: 'Jet Ski',
        model: 'Pro 300',
        year: 2020,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Sailboat Freedom 45',
        carSubtitle: 'Sailboat, Sailing Adventure',
        price: 40000,
        mileage: '200 hours',
        location: 'Chicago, IL',
        engineVolume: 'Sail',
        engineType: 'Wind',
        brand: 'Sailboat',
        model: 'Freedom 45',
        year: 2019,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Kayak Explorer 10',
        carSubtitle: 'Recreational Kayak, Paddling Fun',
        price: 500,
        mileage: 'N/A',
        location: 'Miami, FL',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Kayak',
        model: 'Explorer 10',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Fishing Boat Pro 150',
        carSubtitle: 'Fishing Boat, Angler’s Choice',
        price: 25000,
        mileage: '75 hours',
        location: 'Los Angeles, CA',
        engineVolume: '150 HP',
        engineType: 'Gasoline',
        brand: 'Fishing Boat',
        model: 'Pro 150',
        year: 2021,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Canoe Voyager 14',
        carSubtitle: 'Canoe, Tranquil Paddling',
        price: 800,
        mileage: 'N/A',
        location: 'New York, NY',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Canoe',
        model: 'Voyager 14',
        year: 2020,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Jet Boat Racer X',
        carSubtitle: 'Jet Boat, Adrenaline Rush',
        price: 25000,
        mileage: '30 hours',
        location: 'Chicago, IL',
        engineVolume: '200 HP',
        engineType: 'Gasoline',
        brand: 'Jet Boat',
        model: 'Racer X',
        year: 2019,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Sailboat Odyssey 36',
        carSubtitle: 'Sailboat, Coastal Cruising',
        price: 35000,
        mileage: '150 hours',
        location: 'Miami, FL',
        engineVolume: 'Sail',
        engineType: 'Wind',
        brand: 'Sailboat',
        model: 'Odyssey 36',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Kayak Adventure 12',
        carSubtitle: 'Touring Kayak, Nature Exploration',
        price: 600,
        mileage: 'N/A',
        location: 'Los Angeles, CA',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Kayak',
        model: 'Adventure 12',
        year: 2021,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Speedboat Z2',
        carSubtitle: 'Sport Boat, Thrilling Adventures',
        price: 35000,
        mileage: '60 hours',
        location: 'San Francisco, CA',
        engineVolume: '280 HP',
        engineType: 'Gasoline',
        brand: 'Speedboat',
        model: 'Z2',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Luxury Yacht 850',
        carSubtitle: 'Yacht, Ultimate Luxury',
        price: 180000,
        mileage: '120 hours',
        location: 'Las Vegas, NV',
        engineVolume: '800 HP',
        engineType: 'Diesel',
        brand: 'Luxury Yacht',
        model: '850',
        year: 2021,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Jet Ski Elite 500',
        carSubtitle: 'Personal Watercraft, Unmatched Speed',
        price: 9000,
        mileage: '25 hours',
        location: 'New York, NY',
        engineVolume: '120 HP',
        engineType: 'Gasoline',
        brand: 'Jet Ski',
        model: 'Elite 500',
        year: 2020,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Sailboat Voyager 50',
        carSubtitle: 'Sailboat, Offshore Cruising',
        price: 55000,
        mileage: '250 hours',
        location: 'Chicago, IL',
        engineVolume: 'Sail',
        engineType: 'Wind',
        brand: 'Sailboat',
        model: 'Voyager 50',
        year: 2019,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Kayak Explorer 15',
        carSubtitle: 'Touring Kayak, Scenic Paddling',
        price: 700,
        mileage: 'N/A',
        location: 'Miami, FL',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Kayak',
        model: 'Explorer 15',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Fishing Boat Pro 200',
        carSubtitle: 'Fishing Boat, Angler’s Dream',
        price: 28000,
        mileage: '90 hours',
        location: 'Los Angeles, CA',
        engineVolume: '200 HP',
        engineType: 'Gasoline',
        brand: 'Fishing Boat',
        model: 'Pro 200',
        year: 2021,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Canoe Voyager 16',
        carSubtitle: 'Canoe, Tranquil Waters',
        price: 900,
        mileage: 'N/A',
        location: 'New York, NY',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Canoe',
        model: 'Voyager 16',
        year: 2020,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Jet Boat Extreme X',
        carSubtitle: 'Jet Boat, Extreme Thrills',
        price: 28000,
        mileage: '35 hours',
        location: 'Chicago, IL',
        engineVolume: '220 HP',
        engineType: 'Gasoline',
        brand: 'Jet Boat',
        model: 'Extreme X',
        year: 2019,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Sailboat Odyssey 42',
        carSubtitle: 'Sailboat, Ocean Adventures',
        price: 45000,
        mileage: '200 hours',
        location: 'Miami, FL',
        engineVolume: 'Sail',
        engineType: 'Wind',
        brand: 'Sailboat',
        model: 'Odyssey 42',
        year: 2022,
    },
    {
        type: 'Water Vehicle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Kayak Adventure 18',
        carSubtitle: 'Touring Kayak, Wilderness Exploration',
        price: 800,
        mileage: 'N/A',
        location: 'Los Angeles, CA',
        engineVolume: 'Paddle',
        engineType: 'Human',
        brand: 'Kayak',
        model: 'Adventure 18',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Honda Civic',
        carSubtitle: 'Compact Car, Fuel-Efficient',
        price: 19000,
        mileage: '22,000 km',
        location: 'Boston, MA',
        engineVolume: '1.5 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Compact',
        brand: 'Honda',
        model: 'Civic',
        year: 2021,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Suzuki GSX-R750',
        carSubtitle: 'Sport Motorcycle, High Performance',
        price: 12000,
        mileage: '7,000 km',
        location: 'Denver, CO',
        engineVolume: '0.75 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Suzuki',
        model: 'GSX-R750',
        year: 2022,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'GMC Sierra 1500',
        carSubtitle: 'Full-Size Pickup Truck, Versatile',
        price: 35000,
        mileage: '30,000 km',
        location: 'Las Vegas, NV',
        engineVolume: '5.3 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'GMC',
        model: 'Sierra 1500',
        year: 2021,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ford Focus',
        carSubtitle: 'Compact Car, Stylish and Efficient',
        price: 18000,
        mileage: '20,000 km',
        location: 'San Francisco, CA',
        engineVolume: '1.6 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Compact',
        brand: 'Ford',
        model: 'Focus',
        year: 2022,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Harley-Davidson Iron 883',
        carSubtitle: 'Cruiser Motorcycle, Classic Style',
        price: 13000,
        mileage: '5,000 km',
        location: 'Miami, FL',
        engineVolume: '0.88 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Harley-Davidson',
        model: 'Iron 883',
        year: 2021,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Toyota Tundra',
        carSubtitle: 'Full-Size Pickup Truck, Rugged Performance',
        price: 36000,
        mileage: '28,000 km',
        location: 'New York, NY',
        engineVolume: '5.7 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Toyota',
        model: 'Tundra',
        year: 2022,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Chevrolet Cruze',
        carSubtitle: 'Compact Car, Affordable and Reliable',
        price: 17000,
        mileage: '18,000 km',
        location: 'Los Angeles, CA',
        engineVolume: '1.4 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Compact',
        brand: 'Chevrolet',
        model: 'Cruze',
        year: 2021,
    },
    {
        type: 'Motorcycle',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ducati Panigale V4',
        carSubtitle: 'Superbike, High-Performance Racing',
        price: 22000,
        mileage: '3,000 km',
        location: 'Chicago, IL',
        engineVolume: '1.1 L',
        engineType: 'Gasoline',
        transmission: 'Manual',
        brand: 'Ducati',
        model: 'Panigale V4',
        year: 2022,
    },
    {
        type: 'Car',
        imageSrc:require('@/assets/img/car1.jpg'),

        carTitle: 'Nissan Altima',
        carSubtitle: 'Midsize Sedan, Comfortable Ride',
        price: 20000,
        mileage: '15,000 km',
        location: 'San Francisco, CA',
        engineVolume: '2.5 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Sedan',
        brand: 'Nissan',
        model: 'Altima',
        year: 2021,
    },
    {
        type: 'Truck',
        imageSrc:require('@/assets/img/car1.jpg'),
        carTitle: 'Ford F-150',
        carSubtitle: 'Full-Size Pickup Truck, Versatility',
        price: 34000,
        mileage: '25,000 km',
        location: 'Miami, FL',
        engineVolume: '3.5 L',
        engineType: 'Gasoline',
        transmission: 'Automatic',
        bodyType: 'Pickup Truck',
        brand: 'Ford',
        model: 'F-150',
        year: 2021,
    }

]

export const vehicleType = [
    {
        id:1,
        title: 'Truck',
    },
    {
        id:2,
        title: 'Car',
    },
    {
        id:3,
        title: 'Motorcycle',
    },
    {
        id:4,
        title: 'Water Vehicle',
    },
    {
        id:5,
        title: 'Other',
    }
]


export const vehicleBodyType = [
    {
        id:1,
        title: 'Pickup Truck',
    },
    {
        id:2,
        title: 'Sedan',
    },
    {
        id:3,
        title: 'Compact',
    },
    {
        id:4,
        title: 'Full-Size',
    },
    {
        id:5,
        title: 'Van',
    },
    {
        id:6,
        title: 'Other',
    }
]
export const vehicleModel = [
    {
        id:1,
        title:'F-150'
    },
    {
        id:2,
        title:'Cruze'
    },
    {
        id:3,
        title:'Sierra 1500'
    },
    {
        id:4,
        title:'Iron 883'
    },
    {
        id:5,
        title:'Tundra'
    },
    {
        id:6,
        title:'Civic'
    },
    {
        id:7,
        title:'GSX-R750'
    },
    {
        id:8,
        title:'Altima'
    },
    {
        id:9,
        title:'Panigale V4'
    },
    {
        id:10,
        title:'Odyssey 42'
    },
    {
        id:11,
        title:'Adventure 18'
    },
    {
        id:12,
        title:'Extreme X'
    },
]

export const vehicleBrandType = [
    {
        id:1,
        title: 'Ford'
    },
    {
        id:2,
        title: 'Honda'
    },
    {
        id:3,
        title: 'Nissan'
    },
    {
        id:4,
        title: 'Toyota'
    },
    {
        id:5,
        title: 'Suzuki'
    },
    {
        id:6,
        title: 'Chevrolet'
    },
    {
        id:7,
        title: 'Ducati'
    },
    {
        id:8,
        title: 'Harley-Davidson'
    },
    {
        id:9,
        title: 'GMC'
    },
    {
        id:10,
        title: 'Kawasaki'
    },
    {
        id:11,
        title: 'Yamaha'
    },
    {
        id:12,
        title: 'Sailboat'
    },
]

export const yearData =[
    {
        id:1,
        year: 2022
    },
    {
        id:2,
        year: 2021
    },
    {
        id:3,
        year: 2020
    },
    {
        id:4,
        year: 2019
    },
]


/*
*
        *
        *
        *
        *
        *
        * setVehicleType({ commit }, value) {
            commit('setVehicleType', value)
        },
        setVehicleBodyTypeValue({ commit }, value) {
            commit('setVehicleBodyTypeValue', value)
        },
        setVehicleModelType({ commit }, value) {
            commit('setVehicleModelType', value)
        }*/